version: "3"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - db_vol:/var/lib/mysql/wordpress_db
    restart: always
    networks:
      - inception_network
    image: mariadb
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wp_vol:/var/www/html/wordpress
    env_file:
      - .env
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception_network
    image: wordpress
  nginx:
    build: ./requirements/nginx
    env_file:
      - .env
    container_name: nginx
    volumes:
      - wp_vol:/var/www/html/wordpress
    ports:
      - '443:443'
    depends_on:
      - wordpress
      - redis
    restart: always
    networks:
      - inception_network
    image: nginx
  redis:
    build: ./requirements/redis
    container_name: redis
    restart: always
    networks:
      - inception_network
    image: redis
  ftp:
    build: ./requirements/ftp
    container_name: ftp
    restart: always
    volumes:
      - wp_vol:/home/alae/wordpress
    networks:
      - inception_network
    image: ftp
  resume:
    build: ./requirements/resume
    container_name: resume
    restart: always
    ports:
      - '5050:80'
    networks:
      - inception_network
    image: resume
  adminer:
    build: ./requirements/adminer
    container_name: adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      - inception_network
    image: adminer
  cadvisor:
    build: requirements/Cadvisor
    container_name: Cadvisor
    restart: always
    ports:
      - '8181:8080'
    volumes:
      - /:/rootfs:ro
      - /var/run/:/var/run/:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - inception_network  
    image: cadvisor
volumes:
  wp_vol:
    driver: local
    driver_opts:
      type: noun
      o: bind
      device: /home/ael-korc/data/wordpress_files
  db_vol:
    driver: local
    driver_opts:
      type: noun
      o: bind
      device: /home/ael-korc/data/wp_db
networks:
  inception_network:
    driver: bridge
