version: "3"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - /Users/ael-korc/data/wordpress_db:/var/lib/mysql/wordpress_db
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - /Users/ael-korc/data/wordpress:/var/www/html/wordpress
    env_file:
      - .env
  nginx:
    build: ./requirements/nginx
    env_file:
      - .env
    container_name: nginx
    volumes:
      - /Users/ael-korc/data/wordpress:/var/www/html/wordpress
    ports:
      - '443:443'
    depends_on:
      - wordpress
