version: "3"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    # volumes:
    #   - db_vol:/var/lib/mysql/wordpress_db
    restart: always
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wp_vol:/var/www/html/wordpress
    env_file:
      - .env
    restart: always
  nginx:
    build: ./requirements/nginx
    env_file:
      - .env
    container_name: nginx
    volumes:
      - wp_vol:/var/www/html/wordpress
    ports:
      - '443:443'
    depends_on:
      - wordpress
      - redis
    restart: always
  redis:
    build: ./requirements/redis
    container_name: redis


volumes:
  wp_vol:
    driver: local
    driver_opts:
      type: noun
      o: bind
      device: /Users/ael-korc/Inception/srcs/requirements/wordpress/wordpress_files
  db_vol:
    driver: local
    driver_opts:
      type: noun
      o: bind
      device: /Users/ael-korc/Inception/srcs/requirements/mariadb/wp_db
