FROM debian:bullseye

COPY tools/nginx.sh /etc/nginx/
COPY conf/nginxt.conf /etc/nginx/

RUN apt update
RUN apt install -y nginx
RUN apt install -y openssl
RUN apt install gettext-base -y

CMD ["sh", "/etc/nginx/nginx.sh"]



