FROM debian

COPY tools/nginx.sh /etc/nginx/
COPY conf/nginx.conf /etc/nginx/conf.d/

RUN apt update
RUN apt install -y nginx
RUN apt install -y vim
RUN apt install -y curl
RUN apt install -y openssl
RUN sh /etc/nginx/nginx.sh

CMD ["nginx", "-g", "daemon off;"]



